version: '3.8'

services:
  # Backend Node.js/TypeScript
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mindcare-backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - mindcare-network # Adicione esta linha
    restart: unless-stopped

  # Frontend React Native + Expo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mindcare-frontend-dev
    ports:
      - "8081:8081"   # Metro bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # Expo
      - "19002:19002" # Expo
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    networks:
      - mindcare-network # Adicione esta linha
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  mindcare-network:
    driver: bridge
