import { TrilhaModel } from '../types';

/**
 * Trilha 13 – Controle da Ansiedade (Intermediário – 15 a 20 min)
 */
export const trilhaControleAnsiedade: TrilhaModel = {
  id: 13,
  key: 'trilha-controle-ansiedade',
  name: 'Trilha 13 – Controle da Ansiedade',
  focus: 'Reduzir sintomas ansiosos e melhorar o foco no presente.',
  level: 'Intermediário',
  minMinutes: 15,
  maxMinutes: 20,
  days: [
    {
      day: 1,
      microHabit: 'Respiração 4-7-8 guiada',
      durationMinutes: 15,
      durationLabel: '15 min',
      goal: 'Acalmar corpo e mente',
      benefits: [
        'Reduz a ativação do sistema de alerta',
        'Diminui tensão muscular e ritmo cardíaco',
        'Ajuda a interromper ciclos de ansiedade intensa',
      ],
      howTo: [
        'Sente-se ou deite-se em uma posição confortável e segura.',
        'Inspire pelo nariz por 4 segundos, enchendo o abdômen de ar.',
        'Segure a respiração por 7 segundos, sem forçar além do confortável.',
        'Expire lentamente pela boca por 8 segundos, soltando o ar por completo.',
        'Repita o ciclo de 4-7-8 várias vezes, mantendo a atenção apenas na respiração.',
        'Se a mente se dispersar, apenas volte a focar na contagem e no movimento do ar.',
      ],
    },
    {
      day: 2,
      microHabit: 'Meditação com atenção nos sons ao redor',
      durationMinutes: 18,
      durationLabel: '18 min',
      goal: 'Aumentar foco sensorial',
      benefits: [
        'Ajuda a tirar o foco de pensamentos ansiosos e ruminativos',
        'Fortalece a capacidade de ancorar a atenção em estímulos externos neutros',
        'Promove sensação de presença e conexão com o ambiente',
      ],
      howTo: [
        'Sente-se em um lugar relativamente silencioso, mas onde ainda haja alguns sons ao redor.',
        'Feche os olhos ou suavize o olhar, mantendo o corpo relaxado.',
        'Comece apenas ouvindo: note os diferentes sons (carros, vozes, vento, ruídos internos da casa).',
        'Não tente identificar cada som; apenas perceba que eles vêm e vão.',
        'Sempre que pensamentos ansiosos aparecerem, reconheça-os e volte a focar nos sons.',
        'Permaneça assim até o final do tempo, respirando de forma calma e regular.',
      ],
    },
    {
      day: 3,
      microHabit: 'Escrita de preocupações + plano de ação realista',
      durationMinutes: 20,
      durationLabel: '20 min',
      goal: 'Organizar pensamentos',
      benefits: [
        'Ajuda a separar preocupação útil de preocupação improdutiva',
        'Transforma ansiedade em passos concretos quando possível',
        'Reduz a sensação de confusão mental e sobrecarga',
      ],
      howTo: [
        'Pegue um caderno ou documento no celular.',
        'Divida a página em duas colunas: “Preocupações” e “Plano realista”.',
        'Na primeira coluna, escreva as principais preocupações que estão te incomodando.',
        'Depois, para cada preocupação, pergunte: “O que é possível fazer, de forma realista, sobre isso?”',
        'Na segunda coluna, escreva apenas ações concretas, pequenas e possíveis (ou “nada a fazer agora” quando for o caso).',
        'Ao terminar, escolha uma ou duas ações simples para dar o primeiro passo e aceite que algumas coisas não estão sob seu controle imediato.',
      ],
    },
    {
      day: 4,
      microHabit: 'Exercício físico leve (yoga ou alongamento)',
      durationMinutes: 15,
      durationLabel: '15 min',
      goal: 'Reduzir tensão corporal',
      benefits: [
        'Ajuda a liberar a ansiedade acumulada nos músculos',
        'Aumenta a sensação de leveza e circulação corporal',
        'Integra corpo e mente por meio do movimento consciente',
      ],
      howTo: [
        'Escolha uma sequência curta de yoga suave ou alongamentos que você conheça, ou siga um vídeo curto.',
        'Realize os movimentos devagar, prestando atenção nas sensações do corpo.',
        'Mantenha a respiração fluindo, evitando prendê-la durante o esforço.',
        'Respeite seus limites físicos, sem forçar além do confortável.',
        'Ao final, permaneça alguns instantes parada(o), apenas sentindo o corpo após os movimentos.',
      ],
    },
    {
      day: 5,
      microHabit: 'Técnica 5-4-3-2-1 (identificar sentidos)',
      durationMinutes: 18,
      durationLabel: '18 min',
      goal: 'Trazer atenção para o presente',
      benefits: [
        'Ajuda a interromper picos de ansiedade trazendo a mente para o agora',
        'Usa os cinco sentidos como âncoras de atenção',
        'Reduz sensação de despersonalização ou “estar desconectada(o)”',
      ],
      howTo: [
        'Pare em um lugar onde se sinta razoavelmente segura(o).',
        'Olhe ao redor e identifique mentalmente 5 coisas que você pode ver.',
        'Depois, identifique 4 coisas que você pode tocar (ou imaginar o toque).',
        'Identifique 3 coisas que você pode ouvir.',
        'Identifique 2 coisas que você pode cheirar.',
        'Por fim, identifique 1 coisa que você pode saborear (real ou imaginada).',
        'Faça tudo isso com calma, respirando devagar durante o processo.',
      ],
    },
    {
      day: 6,
      microHabit: 'Caminhada consciente + foco na respiração',
      durationMinutes: 15,
      durationLabel: '15 min',
      goal: 'Diminuir agitação',
      benefits: [
        'Canaliza a energia ansiosa em movimento organizado',
        'Ajuda a regular respiração e ritmo corporal',
        'Cria uma experiência de presença em movimento',
      ],
      howTo: [
        'Escolha um local seguro para caminhar durante alguns minutos.',
        'Comece a caminhar em ritmo confortável, sem pressa.',
        'Coordene a respiração com os passos: por exemplo, inspire em 2 passos e expire em 2 ou 3.',
        'Enquanto caminha, perceba a sensação dos pés tocando o chão e o movimento dos braços.',
        'Se pensamentos acelerados surgirem, note e retorne a atenção para a respiração e os passos.',
      ],
    },
    {
      day: 7,
      microHabit: 'Revisão da semana: anotar gatilhos e avanços',
      durationMinutes: 15,
      durationLabel: '15 min',
      goal: 'Refletir sobre evolução',
      benefits: [
        'Ajuda a identificar situações que mais disparam ansiedade',
        'Permite perceber estratégias que funcionaram melhor para você',
        'Fortalece senso de progresso e aprendizado ao longo do tempo',
      ],
      howTo: [
        'Pegue um caderno ou app de notas em um momento tranquilo.',
        'Pense nos últimos dias e recorde situações em que a ansiedade apareceu com mais força.',
        'Anote esses gatilhos em uma lista.',
        'Em seguida, escreva quais estratégias ou práticas te ajudaram a lidar melhor (por exemplo: respiração, caminhada, escrita).',
        'Por fim, anote um compromisso simples para a próxima semana, baseado no que você aprendeu sobre si mesma(o).',
      ],
    },
  ],
};
